# Generated by Django 2.2.3 on 2019-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
