# Generated by Django 2.2.3 on 2019-07-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20190717_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=20)),
                ('right', models.IntegerField(default=0)),
                ('wrong_result', models.TextField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.TestSet')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
