# Generated by Django 2.2.3 on 2019-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20190712_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
