# Generated by Django 2.2.3 on 2019-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_quiz_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
