# Generated by Django 2.2.3 on 2019-07-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20190717_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='case',
        ),
    ]
