# Generated by Django 2.2.3 on 2019-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_quiz_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='testcase',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
