# Generated by Django 2.2.3 on 2019-07-19 17:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20190718_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='markdown_explanation',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
