# Generated by Django 2.2.3 on 2019-07-19 18:02

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_quiz_markdown_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='markdown_explanation',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
