# Generated by Django 2.2.3 on 2019-07-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20190719_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
