# Generated by Django 2.2.3 on 2019-07-20 21:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20190720_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=markdownx.models.MarkdownxField(blank=True, default=None, null=True),
        ),
    ]
