# Generated by Django 2.2.3 on 2019-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_auto_20190720_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
