# Generated by Django 2.2.3 on 2019-07-26 04:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_auto_20190724_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
