# Generated by Django 2.2.3 on 2019-07-26 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_auto_20190725_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
