# Generated by Django 2.2.3 on 2019-07-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0021_auto_20190726_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryLevel',
            new_name='Difficulty',
        ),
    ]
