# Generated by Django 2.2.3 on 2019-07-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0022_auto_20190726_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='difficulty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.Difficulty'),
        ),
    ]
