# Generated by Django 2.2.3 on 2019-07-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_category_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
