# Generated by Django 2.2.3 on 2019-07-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0024_category_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='number',
            new_name='order',
        ),
    ]
