# Generated by Django 2.2.3 on 2019-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0025_auto_20190726_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
