# Generated by Django 2.2.3 on 2019-08-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0028_answer_print_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='print_result',
            new_name='printed',
        ),
    ]
