# Generated by Django 2.2.3 on 2019-08-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0029_auto_20190801_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='printed',
            new_name='stdout',
        ),
    ]
