# Generated by Django 2.2.3 on 2019-08-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0030_auto_20190801_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSet',
            new_name='Testcase',
        ),
    ]
