# Generated by Django 2.2.3 on 2019-08-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0031_auto_20190801_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='wrong_result',
            new_name='output',
        ),
    ]
