# Generated by Django 2.2.3 on 2019-08-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0033_badge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='condition',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
