# Generated by Django 2.2.3 on 2019-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0034_auto_20190801_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='html',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
