# Generated by Django 2.2.3 on 2019-08-03 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0038_quiz_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order'], 'verbose_name_plural': 'Quizs'},
        ),
        migrations.AddField(
            model_name='badge',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.BadgeType'),
        ),
    ]
