# Generated by Django 2.2.3 on 2019-08-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0041_badge_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
