# Generated by Django 2.2.3 on 2019-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0042_difficulty_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['order'], 'verbose_name_plural': 'Badges'},
        ),
        migrations.AddField(
            model_name='badge',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
