# Generated by Django 2.2.3 on 2019-08-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0043_auto_20190804_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
