# Generated by Django 2.2.3 on 2019-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0044_quiz_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-order'], 'verbose_name_plural': 'Quizs'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
