# Generated by Django 2.2.3 on 2019-08-16 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0045_auto_20190816_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
