# Generated by Django 2.2.3 on 2019-08-16 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0046_auto_20190816_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='example',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
