# Generated by Django 2.2.3 on 2019-08-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0051_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
