# Generated by Django 2.2.3 on 2019-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0054_auto_20190824_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
