# Generated by Django 2.2.3 on 2019-08-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0056_answer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
