# Generated by Django 2.2.3 on 2019-08-25 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0057_auto_20190824_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 24, 18, 40, 31, 609945)),
        ),
    ]
