# Generated by Django 2.2.3 on 2019-08-25 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0058_auto_20190824_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 25, 1, 41, 53, 619974, tzinfo=utc)),
        ),
    ]
