# Generated by Django 2.2.3 on 2019-08-25 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0060_auto_20190824_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
