# Generated by Django 2.2.3 on 2019-09-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0061_auto_20190824_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.CustomUser')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Quiz')),
            ],
        ),
    ]
