# Generated by Django 2.2.3 on 2019-09-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0063_auto_20190907_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('custom_user', 'quiz')},
        ),
    ]
