# Generated by Django 2.2.3 on 2019-09-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0065_quiz_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='QuizScore',
        ),
    ]
