# Generated by Django 2.2.3 on 2019-09-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0066_auto_20190907_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['title'], name='list_quiz_title_ac5e79_idx'),
        ),
    ]
