# Generated by Django 2.2.3 on 2019-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0068_auto_20190917_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
