# Generated by Django 2.2.3 on 2019-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0069_auto_20190917_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
