# Generated by Django 2.2.3 on 2019-09-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0070_auto_20190917_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='expected_answer',
            new_name='expected_output',
        ),
    ]
