# Generated by Django 2.2.3 on 2019-09-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0071_auto_20190919_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='expected_answer',
            new_name='expected_output',
        ),
    ]
