# Generated by Django 2.2.3 on 2019-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0072_auto_20190919_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='expected_stdout',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_stdout',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
