# Generated by Django 2.2.3 on 2019-09-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0073_auto_20190919_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
    ]
