# Generated by Django 2.2.3 on 2019-09-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0074_remove_answer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.CustomUser'),
        ),
    ]
