# Generated by Django 2.2.3 on 2019-09-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0075_answer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name',
            new_name='custom_user',
        ),
    ]
