# Generated by Django 2.2.3 on 2019-09-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0076_auto_20190919_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='custom_user',
            new_name='customuser',
        ),
        migrations.RenameField(
            model_name='quizscore',
            old_name='custom_user',
            new_name='customuser',
        ),
        migrations.AlterUniqueTogether(
            name='quizscore',
            unique_together={('customuser', 'quiz')},
        ),
    ]
