# Generated by Django 2.2.3 on 2019-09-29 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0079_auto_20190923_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
