# Generated by Django 2.2.3 on 2019-10-02 03:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0080_answer_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
