# Generated by Django 2.2.3 on 2019-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0082_auto_20191004_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoint',
            old_name='point_type',
            new_name='pointtype',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterIndexTogether(
            name='userpoint',
            index_together={('customuser', 'date', 'pointtype')},
        ),
        migrations.RemoveField(
            model_name='userpoint',
            name='point',
        ),
    ]
