# Generated by Django 2.2.3 on 2019-10-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0083_auto_20191004_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='customuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.CustomUser'),
        ),
    ]
