# Generated by Django 2.2.3 on 2019-10-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0085_auto_20191004_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='score',
            new_name='point',
        ),
    ]
