# Generated by Django 2.2.3 on 2019-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0086_auto_20191004_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=10),
        ),
    ]
