# Generated by Django 2.2.3 on 2019-10-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0089_auto_20191010_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.CustomUser'),
        ),
        migrations.AlterIndexTogether(
            name='answer',
            index_together={('date', 'right')},
        ),
    ]
