# Generated by Django 2.2.3 on 2019-10-20 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0090_auto_20191012_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, default='<table border="1" cellpadding="1" cellspacing="1" class="table table-bordered">\n    <tbody>\n        <tr>\n            <td>\n                <strong>Block</strong>\n            </td>\n        </tr>\n    </tbody>\n</table>\n', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_stdout',
            field=models.TextField(default=''),
        ),
    ]
