# Generated by Django 2.2.3 on 2019-10-20 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0092_auto_20191020_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_header',
            field=models.TextField(default='def solve(num):'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='example',
            field=ckeditor.fields.RichTextField(default='<p>Example 1:</p>\n<table border="1" cellpadding="1" cellspacing="1" class="table table-bordered">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p><strong>Input</strong>:&nbsp;</p>\n\t\t\t<p><strong>Output</strong>:&nbsp;</p>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>&nbsp;</p>\n<p>Example 2:</p>\n<table border="1" cellpadding="1" cellspacing="1" class="table table-bordered">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p><strong>Input</strong>:&nbsp;</p>\n\t\t\t<p><strong>Output</strong>:&nbsp;</p>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>\n'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
