# Generated by Django 2.2.3 on 2019-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0095_auto_20191020_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer_header',
            field=models.TextField(blank=True, default='def solve(num):', null=True),
        ),
    ]
