# Generated by Django 2.2.3 on 2019-10-20 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0097_auto_20191020_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='expected_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='expected_stdout',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='stdout',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_header',
            field=models.TextField(blank=True, default='def solve(num):'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, default='<table border="1" cellpadding="1" cellspacing="1" class="table table-bordered">\n    <tbody>\n        <tr>\n            <td>\n                <strong>Block</strong>\n            </td>\n        </tr>\n    </tbody>\n</table>\n'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_stdout',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(blank=True, default=''),
        ),
    ]
