# Generated by Django 2.2.3 on 2019-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0098_auto_20191020_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
